### ISSUE TITLE
jQuery Tooltips not working with jQuery 1.5.2 or jQuery 1.6

### ISSUE THREAD

**Issue by avitus** [jquerytools/www#6]
Issue is described fully  here.

http://stackoverflow.com/questions/5903676/jquery-tools-tooltip-inserting-empty-style-attribute-on-tip

Short version:

In jQuery 1.5.2 and later, and empty style="" is inserted on the <div class="tooltip">

**Comment by alibby251** [comment]
We are updating jQuery Tools to version 1.2.6, which will have support for jQuery 1.6.2 - I would suggest holding off using anything later than 1.4.2. with jQuery Tools 1.2.5, and then upgrading as soon as we release it.

**Comment by avitus** [comment]
I will be out of the office and country until Sept 8th. Please contact my assistant, Wendy (wendy@scalevp.com) for anything urgent.

**Comment by i8ramin** [comment]
We were running version 1.2.5 of the tooltips code and it had some issues with jQuery 1.5.2+ (1.5.1 seems to be ok) ... did a diff of 1.2.5 and 1.2.6 of jquery tools and narrowed down the issue to this line inside of the show/hide functions.

// 1.2.5
e = e || $.Event();

// 1.2.6
e = $.Event();

So, it seems like we always want a new jQuery Event and not the originating event object. That fixed the issue for us.

**Comment by alibby251** [comment]
I'm closing this issue - although the fix will be useful for anyone who needs it, version 1.2.5 of Tools was never officially compatibility tested with jQuery 1.5 or 1.6, so I can't guarantee it will work. Since this original request was logged though, we have released Tools 1.2.6 which has official support for jQuery 1.6.4; we are working to release the next version with support for the 1.7.x branch of jQuery.
